name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches:
      - master
    paths:
      - 'appconfig/dev.json'
jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: fabiocosta07/ts-action-aws-appconfig-deploy@v1.1
        with:
          configPath: 'appconfig/dev.json'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.time }}"
  # hello_world_job:
  #   runs-on: ubuntu-latest
  #   name: A job to say hello
  #   steps:
  #     - name: Hello world action step
  #       id: hello
  #       uses: fabiocosta07/action-aws-appconfig-deploy@v1.2
  #       with:
  #         who-to-greet: 'Mona the Octocat'
  #     # Use the output from the `hello` step
  #     - name: Get the output time
  #       run: echo "The time was ${{ steps.hello.outputs.time }}"
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run : ls
  #     - run: pwd
  #     - run: aws s3 ls
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: 'us-east-1'
